### PR TITLE
Option to save a collection to the browser's bookmarks

### PR DESCRIPTION
**Pull request by AmineI**
Implements the project roadmap's card "Add a collection to the bookmarks"

Opening as draft as it can't be merged until #48 is. If #48 is refused I'll just cherry pick what's needed from it and edit it to work with the current storage system

- [x] Adds a user-facing button to add a collection to the bookmarks, using the `SaveCollectionAsBookmarks()` function defined in #48 

- [x] Rebase this branch on major-2.0 once #48 is merged, or rework the PR if #48 is refused.

---
Edit by @XFox111:
TODO: Update translations:
- [x] RU
- [ ] IT
- [x] PT_BR
- [ ] ES
- [ ] ZH_CN

### CODE REVIEW

**Comment by AmineI** [comment]
Carefully rebased on major-2.0, and retested the feature ! Now ready for review :) . I only have to machine translate the strings for other languages now.

**Review by XFox111 — CHANGES_REQUESTED** [review]
Great work! We need now to update translations (I've updated PR description). But I think bookmarks tree can be improved. Besides, I've found that if user saves two collections with the same name, they merge into one. Here's the scheme of what I mean:
image

**Comment by XFox111** [comment]
> Hi, it seems that if I delete a target branch of a PR it automatically closes, and I can't rebase it or reopen anymore... Well, I didn't see that coming. Should rebase this earlier, sorry. So, I guess, you need to create another one

**Comment by AmineI** [comment]
I'll look into how to improve the tree like that, it would definitely be better to not clutter the bookmark bar ! 

As for merging two collections, the [API docs](https://developer.chrome.com/docs/extensions/reference/bookmarks/) seems to indicate no other way to check if a folder exists than iterating on the nodes to find it - hopefully there is a way to iterate only on the current tree levels, and not the whole subtree, I'll look into this !

Otherwise, maybe naming the folders "<collection name> - <creation date>" would be an acceptable solution, that info could be even more helpful than a (1) after the name. What do you prefer ?

**Comment by XFox111** [comment]
> Otherwise, maybe naming the folders " - " would be an acceptable solution, that info could be even more helpful than a (1) after the name. What do you prefer ?

I didn't quite catch the idea. Could you elaborate please?

**Comment by AmineI** [comment]
> > Otherwise, maybe naming the folders " - " would be an acceptable solution, that info could be even more helpful than a (1) after the name. What do you prefer ?
> 
> I didn't quite catch the idea. Could you elaborate please?

Ah, I didn't notice the most important part disappeared - it's my bad, I forgot markdown does not like `<>` symbols. 

I was suggesting `"<collection name> - <creation date>"` (instead of `"<collection name> (1)"`, `"<collection name> (2)"`, and so on)

**Comment by XFox111** [comment]
Oh, I got it. Yeah, I guess this is better idea

**Pull request closed without merging**
