### PR TITLE
Added a tooltip explaining how to set specific tabs aside

### PR DESCRIPTION
**Pull request by AmineI**
Added a tooltip explaining how to set specific tabs aside. The goal is to help with discoverability : even though this feature was added since quite some time, people still ask for it in the extension store reviews. 

The tooltip is displayed when hovering a question mark icon. This icon is from Segoe MDL2 Assets like the other icons, to remain consistent :)

image

The tooltip was properly added in the localization files, but only in english, as I don't know any of the other supported languages.

### PR Checklist
- [x] Add an icon and a tooltip to help discover the feature
- [x] English localization
- [x] Other localizations

### CODE REVIEW

**Comment by XFox111** [comment]
@amandafilizola, @Dustin-Jiang, @blackcat-917, @Wafflects, hello, guys! Can you please help us to translate this string onto your languages?
```
Tip: You can set aside specific tabs by selecting them (by holding CTRL or SHIFT and clicking on the tabs) before clicking on the TabsAside extension
```
P.S. Would you mind if I'll ask you about some other translations from time to time?

**Comment by amandafilizola** [comment]
Sure! Do you want me to make another PR or do I just post it here for you to fetch?

**Comment by XFox111** [comment]
I guess, you can commit to the PR (not sure if GitHub allows this tho) or make a separate PR. Actually, I can handle it myself, but I think it will be better for you to make a proper contribution so you will appear on the project's contributors list

**Comment by amandafilizola** [comment]
separate PR open on #60 :smile:

**Comment by blackcat-917** [comment]
I've opened [a PR](https://github.com/AmineI/TabsAsideExtension/pull/1) at [Aminel:select-tabs-discoverability](https://github.com/AmineI/TabsAsideExtension/tree/select-tabs-discoverability)

**Comment by AmineI** [comment]
Accepted @blackcat-917 it localization, thanks for your help !

**Comment by AmineI** [comment]
> you can commit to the PR (not sure if GitHub allows this tho)
@XFox111, since the PR is against your repo, and I ticked the "Allow edits from maintainers" checkbox, you have the right to add commits directly to it, but other people don't :( 

> separate PR open on #60 😄

Nice ! Thank you ! I'm not sure how to proceed since both you @amandafilizola and @blackcat-917 took different approachs. (PR against upstream vs PR against my fork)
Accepting both should be fine in this case - but if needed I can merge #60 into this branch manually 🙂

**Review by XFox111 — APPROVED** [review]

**Comment by XFox111** [comment]
One more PR is completed. Great job everyone!

**Pull request merged**
